txxnrd/Blurting_front

lib/pages/blurtingTab/blurting.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: Blurting createdAt 9시간 시차 수정

---

lib/Utils/utilWidget.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat: 귓속말 걸기 클릭 시 미세한 진동 주기

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
lib/signupquestions/email.dart
lib/signupquestions/image.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:email reload

---

lib/config/app_config.dart
lib/main.dart
pubspec.lock
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat :env-added

---

lib/settings/setting.dart
lib/signupquestions/email.dart
lib/signupquestions/height.dart
lib/signupquestions/hobby.dart
lib/signupquestions/image.dart
lib/signupquestions/mbti/mbti.dart
lib/signupquestions/personality.dart
lib/signupquestions/phonenumber.dart
lib/signupquestions/religion.dart
lib/signupquestions/sex.dart
lib/signupquestions/sexualpreference.dart
lib/signupquestions/smoke.dart
lib/signupquestions/university.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

refactor:signup question 뒤로가기 등 수정

---

lib/pages/myPage/MyPageEdit.dart
lib/settings/setting.dart
lib/settings/url_link.dart
lib/signupquestions/activeplace.dart
lib/signupquestions/height.dart
lib/signupquestions/token.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

refactor: settings

---

lib/pages/myPage/Utils.dart
lib/token.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

missing-files-added

---

lib/config/app_config.dart
lib/pages/homeTab/Home.dart
lib/signupquestions/phonenumber.dart
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

home-scroll-down-made

---

lib/pages/homeTab/Home.dart
lib/pages/myPage/MyPage.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: home scroll

---

lib/pages/blurtingTab/blurting.dart
lib/pages/homeTab/Home.dart
lib/pages/myPage/MyPage.dart
lib/pages/whisperTab/chattingList.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: header-position-fixed

---

ios/Podfile.lock
lib/pages/myPage/MyPage.dart
lib/signupquestions/email.dart
pubspec.lock
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat:image-detail-added

---

lib/pages/myPage/MyPage.dart

feat: index-added

---

lib/pages/myPage/MyPage.dart
lib/signupquestions/height.dart
lib/signupquestions/hobby.dart
lib/signupquestions/image.dart
lib/signupquestions/major.dart
lib/signupquestions/personality.dart
lib/signupquestions/religion.dart
lib/signupquestions/sexualpreference.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:photo-quality-fixed

---

lib/pages/myPage/MyPageEdit.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:mypageedit-fixed

---

lib/mainApp.dart
lib/pages/myPage/mypage_edit.dart
lib/pages/whisper_tab/profileCard.dart
lib/signup_questions/activeplace.dart
lib/signup_questions/mbti/mbti.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:mypageedit

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/home_tab/Home.dart
lib/pages/myPage/mypage_edit.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:my page button error fixed

---

lib/signup_questions/universitylist.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

scnu-fixed

---

lib/StartPage/startpage.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/useGuide/useguidepageone.dart
lib/settings/setting.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: blurting-title-fixed

---

lib/signup_questions/universitylist.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix:hongdae-fixed

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/home_tab/Home.dart
lib/pages/myPage/MyPage.dart
lib/pages/policy/policyOne.dart
lib/pages/useGuide/useguidepagetwo.dart
lib/pages/whisper_tab/chattingList.dart
lib/settings/setting.dart

1. feat: 
-
2. fix: 
- 명예의 전당
- 버튼 이름 수정,
- blurting,connect 위치 내림
<br>
- 
<br>
-

fix: details

---

lib/StartPage/alreadyuser.dart
lib/Utils/provider.dart
lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/home_tab/Home.dart
lib/pages/myPage/mypage_edit.dart
lib/pages/whisper_tab/chattingList.dart
lib/pages/whisper_tab/whisper.dart
lib/settings/setting.dart

정
1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 100자, mvp 카드, 경고문 수

---

lib/signup_questions/Alcohol.dart
lib/signup_questions/Utils.dart
lib/signup_questions/activeplace.dart
lib/signup_questions/email.dart
lib/signup_questions/height.dart
lib/signup_questions/hobby.dart
lib/signup_questions/image.dart
lib/signup_questions/major.dart
lib/signup_questions/mbti/mbti.dart
lib/signup_questions/personality.dart
lib/signup_questions/phonenumber.dart
lib/signup_questions/religion.dart
lib/signup_questions/sex.dart
lib/signup_questions/sexualpreference.dart
lib/signup_questions/smoke.dart
lib/signup_questions/university.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat : email page re-send

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 화살표 날리기

---

lib/pages/blurting_tab/blurting.dart
lib/pages/blurting_tab/groupChat.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: day 0, day 1 -> rhcla

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/blurting_tab/groupChat.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 화살표 보내고 다른 탭 갔을 때 에러, groupChat duplicated key error

---

lib/Utils/util_widget.dart
lib/mainApp.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/myPage/mypage_edit.dart
lib/pages/whisper_tab/profileCard.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 신고하기 overflow

---

lib/Utils/util_widget.dart
lib/pages/home_tab/Home.dart
lib/pages/whisper_tab/chattingList.dart
lib/pages/whisper_tab/whisper.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 채팅방 나가기 경고  문구 수정

---

lib/pages/blurting_tab/blurting.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

add: 주석? 뭐 햇더라

---

lib/main.dart
lib/pages/home_tab/alarm.dart
lib/pages/myPage/mypage_edit.dart
lib/pages/myPage/point_history.dart
lib/settings/setting.dart
lib/signup_questions/email.dart
lib/signup_questions/image.dart
lib/token.dart

1.회원가입시 이메일 안나오는것 수정
2.설정에 사용설명서 추가
3. 알림, 포인트 내역 화면에 제목 수정
4. mypageedit에서 mbti 선택해도 버튼 색 안 바뀌는 거 수정.
<br>
- 
<br>
-

fix : email 

---

lib/Utils/provider.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/home_tab/Home.dart
lib/pages/home_tab/alarm.dart
lib/pages/myPage/mypage_edit.dart
lib/pages/myPage/point_history.dart
lib/pages/useGuide/useguidepagefour.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: whisper push 방법, 자잘한 부분 수정

---

lib/Utils/provider.dart
lib/Utils/util_widget.dart
lib/config/app_config.dart
lib/main.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/whisper_tab/whisper.dart
lib/settings/setting.dart
lib/token.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat: reply function added

---

lib/Utils/provider.dart
lib/Utils/util_widget.dart
lib/main.dart
lib/pages/blurting_tab/groupChat.dart
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat: reply added

---

lib/Utils/util_widget.dart
lib/main.dart
lib/pages/policy/policyOne.dart
lib/pages/useGuide/useguidepageeight.dart
lib/pages/useGuide/useguidepagefour.dart
lib/signup_questions/Utils.dart
lib/signup_questions/email.dart
lib/signup_questions/university.dart
lib/signup_questions/welcomepage.dart
pubspec.lock
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix : email-real fixed

---

lib/Utils/util_widget.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 귓속말 걸기 찐막

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/whisper_tab/whisper.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 전체 화면 요소들 정렬 맞추기

---

lib/Utils/util_widget.dart
lib/main.dart
lib/pages/myPage/MyPage.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

force update 미완성

---

lib/Utils/util_widget.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

Jw0202058@animation

---

lib/signup_questions/email.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

feat : email-added

---

lib/Utils/util_widget.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/whisper_tab/profileCard.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: 세 번째 화살표 에러, feat: 신고 완료 snackbar

---

lib/Utils/util_widget.dart
lib/config/app_config.dart
lib/pages/blurting_tab/blurting.dart
lib/pages/blurting_tab/dayAni.dart
lib/pages/blurting_tab/groupChat.dart
lib/pages/blurting_tab/matchingAni.dart
lib/pages/home_tab/Home.dart
lib/pages/myPage/point_history.dart
pubspec.yaml

1. feat: 
- 광고 기능 추가
- 일일호프용 버튼 추가
2. fix: 
- null
<br>
- 일일호프 매칭 시스템 개편
<br>
- 굉정원 굉장하다!!

Taeyun@daily drink

---

lib/pages/blurting_tab/matchingAni.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: event error

---

lib/pages/home_tab/eventGroup.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: socket initialize, 답변 fetch

---

lib/pages/home_tab/Home.dart
lib/pages/my_page/point_history.dart
lib/pages/whisper_tab/whisper.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix :refactoring done

---

lib/pages/home_tab/event.dart

1. feat: 
-
2. fix: 
- 
<br>
- 
<br>
-

fix: iSended
